### ISSUE TITLE
Crash after a while

### ISSUE THREAD

**Issue by azorkai** [therealtear/discord-nitro-generator#20] opened 2021-01-12 19:51 UTC
After 5-6 minutes, the app crashes. It shows a gray error message but I can't catch it because the window is closed so fast.

**Comment by garrettpark** [comment] 2021-01-13 19:25
This happens for me so to fix it:
I added a simple catch error and log it to console code to the bottom of app.js
`process.on('uncaughtException', function(err) {
  console.log(err);
});`

**Comment by garrettpark** [comment] 2021-01-13 19:27
The most common issue is ECONNRESET
According to google that is caused by the other side of the proxy closed its connection unexpectedly

**Comment by therealtear** [comment] 2021-01-13 19:29
> The most common issue is ECONNRESET
> According to google that is caused by the other side of the proxy closed its connection unexpectedly

yea it happens when you run out of proxies sometimes or like u said they closw

**Closed** 2021-01-13 19:32 UTC
